export { default as ContactPage } from './ContactPage'
export { default as AboutPage } from './AboutPage'
export { default as FaqPage } from './FaqPage'
export { default as PrivacyPage } from './PrivacyPage'
export { default as TermsPage } from './TermsPage'
export { default as ShippingPage } from './ShippingPage'
export { default as ReturnsPage } from './ReturnsPage'
