// ============================================================================
// ElectroKart — Contact Controller
// ============================================================================
// Processes Contact Us inquiries, generating and sending emails via SMTP.
// ============================================================================

import { Request, Response } from 'express';
import nodemailer from 'nodemailer';
import { env } from '../config/env.js';
import { ApiResponse, asyncHandler, ApiError } from '../utils/index.js';

/**
 * Handles sending contact inquiry emails.
 */
export const sendContactEmail = asyncHandler(async (req: Request, res: Response) => {
  const { name, email, subject, message } = req.body;

  const smtpUser = env.GMAIL_USER || 'u.k.s200503@gmail.com';
  const smtpPass = env.GMAIL_APP_PASSWORD;

  if (!smtpPass || smtpPass === 'placeholder_app_password' || smtpPass === 'your_gmail_app_password_here') {
    throw ApiError.internal('Contact SMTP service is not configured. Please define GMAIL_APP_PASSWORD in your environment.');
  }

  // Create transporter using explicit host and port 465 (secure SSL)
  // This is more robust on certain hosting environments than the 'gmail' service alias.
  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    family: 4, // Force IPv4 to prevent IPv6 ENETUNREACH error on host environment
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
    connectionTimeout: 10000, // 10 seconds connection timeout limit
    greetingTimeout: 10000,
  } as any);

  const mailOptions = {
    from: `"Short Circuit Contact Form" <${smtpUser}>`,
    to: 'sales.shortcircuit@gmail.com',
    replyTo: email,
    subject: `Contact inquiry: ${subject}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 25px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <h2 style="color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-top: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">New Contact Inquiry</h2>
        <p style="font-size: 15px; color: #475569; line-height: 1.5; margin-bottom: 25px;">You have received a new inquiry from the Short Circuit Contact Us page:</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 25px;">
          <tr>
            <td style="padding: 10px 0; font-weight: bold; width: 120px; color: #1e293b; border-bottom: 1px solid #f1f5f9; vertical-align: top; font-size: 14px;">Inquirer Name:</td>
            <td style="padding: 10px 0; color: #334155; border-bottom: 1px solid #f1f5f9; font-size: 14px;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; font-weight: bold; width: 120px; color: #1e293b; border-bottom: 1px solid #f1f5f9; vertical-align: top; font-size: 14px;">Reply Email:</td>
            <td style="padding: 10px 0; color: #4f46e5; border-bottom: 1px solid #f1f5f9; font-size: 14px;"><a href="mailto:${email}" style="color: #4f46e5; text-decoration: none;">${email}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px 0; font-weight: bold; width: 120px; color: #1e293b; border-bottom: 1px solid #f1f5f9; vertical-align: top; font-size: 14px;">Subject:</td>
            <td style="padding: 10px 0; color: #1e293b; border-bottom: 1px solid #f1f5f9; font-size: 14px; font-weight: 500;">${subject}</td>
          </tr>
        </table>
        
        <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 18px; margin-top: 15px;">
          <h4 style="margin: 0 0 10px 0; color: #1e293b; font-size: 14px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">Message Details:</h4>
          <p style="margin: 0; color: #334155; font-size: 14px; line-height: 1.6; white-space: pre-wrap; font-family: inherit;">${message}</p>
        </div>
        
        <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 30px 0 20px 0;" />
        <p style="font-size: 12px; color: #94a3b8; text-align: center; margin-bottom: 0;">This notification email was automatically generated by the Short Circuit system.</p>
      </div>
    `,
  };

  await transporter.sendMail(mailOptions);

  res.status(200).json(
    new ApiResponse(200, null, 'Message sent successfully. We will get back to you shortly.')
  );
});
